embed_assets: on
package_assets: on

javascripts:
  common: 
    - public/javascripts/jquery-1.4.4.js
    - public/javascripts/jquery-ui-1.8.7.custom.js
    - public/javascripts/jquery.utils.js
    - public/javascripts/ajax.js
    - public/javascripts/application.js
    
  travel_card:
    - public/javascripts/travel_card.js

stylesheets:
  common:
    - public/stylesheets/wavelineup3.css    