embed_assets: datauri 
package_assets: on
gzip_assets: off

javascripts:
  common: 
    - public/javascripts/jquery-1.4.4.js
    - public/javascripts/jquery-ui-1.8.7.custom.js
    - public/javascripts/jquery.utils.js
    - public/javascripts/autoresize.jquery.min.js
    - public/javascripts/ajax.js
    - public/javascripts/application.js
    
  practice_room:
    - public/javascripts/autosave.js
    - public/javascripts/travel_card.js
    - public/javascripts/visit.js

stylesheets:
  common:
    - public/stylesheets/wavelineup3.css    
    - public/stylesheets/wavelineup3_print.css    
